### ISSUE TITLE
Dynamic Configuration for Source and Target

### ISSUE THREAD

**Issue by doyoubi** [aliyun/redis-shake#283]
It would be great if RedisShake supports dynamic configuration for source and target through HTTP API. This could be very useful when using RedisShake as a long-running service.

**Comment by baronwangr** [comment]
it's a disclaimer that the redisshake tool is NOT supposed to be used as a long-running sync-ing service.
It's simply because that it is based on the PSYNC protocol that can't provide a stable replication stream(because of replication buffer and FULL sync mechanism that will destroy the target data). The reason lays on redis-server side.

So a dynamic configuration of source/target is irrelevant.
