### ISSUE TITLE
Source as azure redis and Target as open source redis

### ISSUE THREAD

**Issue by a0a0996** [aliyun/redis-shake#606]
I am getting the below error while migrating the data outside the azure redis. It is showing the ERR command is disabled, how do we enable it and what is work around. The error logs are:-

2023/05/15 16:24:12 [INFO] DbSyncer[0] psync connect 'testa-ebafb6cb-redis.redis.cache.windows.net:6380' with auth type[auth] OK!
2023/05/15 16:24:12 [PANIC] **repl listening-port failed[-ERR Command disallowed]**
[stack]: 
    2   github.com/alibaba/RedisShake/redis-shake/common/utils.go:142
            github.com/alibaba/RedisShake/redis-shake/common.SendPSyncListeningPort
    1   github.com/alibaba/RedisShake/redis-shake/dbSync/syncBegin.go:41
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).sendPSyncCmd
    0   github.com/alibaba/RedisShake/redis-shake/dbSync/dbSyncer.go:113
            github.com/alibaba/RedisShake/redis-shake/dbSync.(*DbSyncer).Sync

**Comment by suxb201** [comment]
This error occurs because your Redis account does not have permission to execute the `REPLCONF` and `PSYNC` commands. You can submit a ticket to Azure support to inquire about the possibility of enabling the `PSYNC` command on your Redis instance.
ref：https://github.com/tair-opensource/RedisShake/issues/573
